### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by ykl7** [bricksdont/WMT19RefDA#1]
The display starts to flicker when hitting the Submit button and I need to click the button twice to go ahead with it.

Browser: Safari
OS: Mojave

**Comment by bricksdont** [comment]
Thanks for reporting! I am not sure Safari is supported, can you please try in a different browser such as Firefox or Chrome?

**Comment by bricksdont** [comment]
Also, Turkle tasks have a task ID that shows in the URL:

    https://wmt19.waypost.net/turkle/task/9611/

After clicking the <kbd>Submit</kbd> button once, does the task ID (9611 in the example above) change?

**Comment by ykl7** [comment]
I switched to Chrome on seeing your suggestion. I completed one task on Safari but did not notice what you described.

**Comment by bricksdont** [comment]
Could you please clarify:
- Did switching to Chrome solve your problem? (having to click the Submit button twice)
- What do you mean by not noticing what I describe: did the task ID in the URL change after clicking the Submit button for the first time (on Safari, when the display flickers instead of taking you to the next task)?

Thanks

**Comment by ykl7** [comment]
* Switching to Chrome solved the issue
* I did not notice if the task ID in the URL changed every time I clicked the Submit button. I do not think it did since my session was preserved and I was able to finish that task.

**Comment by bricksdont** [comment]
Ok, thanks! Then I will close the issue for now. Please feel free to reopen if you run into this problem again.
