### ISSUE TITLE
Save intermediate work?

### ISSUE THREAD

**Issue by myleott** [bricksdont/WMT19RefDA#4]
I accidentally refreshed the page half-way through a Zh-En HIT and it seems that all my annotations were lost. These HITs take close to an hour to complete, is there no way to recover intermediate annotations?

**Comment by bricksdont** [comment]
Yes, you should be able to recover an "abandoned" task. For me, the UI shows such a button if I leave the annotations page before submitting, see screenshot.

<img width="1265" alt="Screen Shot 2019-05-26 at 15 18 51" src="https://user-images.githubusercontent.com/12611348/58382385-c6aea880-7fc9-11e9-90df-2c3f7e0f9530.png">

**EDIT:** Just tested specifically to refresh the page instead of leaving it. You are right: in this case all annotations are lost.

Will discuss if we can update the system to avoid this behaviour.

**Comment by bricksdont** [comment]
We won't be able to change the system to add this improvement. I will make sure this is added from the start next year.

**Comment by myleott** [comment]
Just lost another one, I don't think the "Resume working on Task" functionality works either :(

**Comment by bricksdont** [comment]
If you refresh the page, then yes, unfortunately annotations are lost immediately. This is because of the way annotations are saved right now (as modifications to the DOM).

Resuming a task worked for me on several occasions when I left the task page.

**Comment by myleott** [comment]
> Resuming a task worked for me on several occasions when I left the task page.

Hmm, I can’t seem to get that functionality to work (and it’d be very helpful if it did, given the length of the Zh-En HITs).

I just tried this: accept a HIT and label one. Leave task page. Renavigate to task page. Click the “Resume” banner. Unfortunately the counter has been reset to 0.

Any suggestions on how to get this to work?

**Comment by bricksdont** [comment]
I just tested again and you are right: sentence counter is reset to 0. Sorry!

But using the "back" button in the browser works for me. Maybe this helps.
